[envs.default]
installer = "uv"
post-install-commands = [
    "- pre-commit install",
]

[envs.hatch-test]
extra-dependencies = [
    "pytest-cov",
]

[[envs.hatch-test.matrix]]
python = [
    "3.11",
    "3.12",
    "3.13",
]

[envs.hatch-test.scripts]
run-cov = "pytest{env:HATCH_TEST_ARGS:} {args:tests} --cov-config=pyproject.toml --cov=hatch_project_name --cov-branch --cov-report=term-missing"
run = "run-cov --no-cov"
cov-combine = "exit 0"
cov-report = "exit 0"

[envs.hatch-static-analysis]
config-path = "ruff_defaults.toml"
dependencies = [
    "ruff==0.11.0",
]

[envs.type-check]
extra-dependencies = [
    "mypy",
    "pytest-cov",
]

[envs.type-check.scripts]
run = "mypy {args:hatch_project_name tests}"
