name: build

on:
  push:
    tags:
    - v*

concurrency:
  group: build-${{ github.head_ref }}

jobs:
  build:
    name: Build wheel and source distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install Hatch
      run: pip install --upgrade hatch

    - name: Build
      run: hatch build

    - uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: dist
        if-no-files-found: error

  publish:
    name: Publish release
    needs:
    - build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v5
      with:
        name: artifacts
        path: dist

    - name: Push build artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
